repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: double-quote-string-fixer

  - repo: https://github.com/prettier/prettier
    rev: 1.17.1
    hooks:
      - id: prettier