name: talks
channels:
    - conda-forge
dependencies:
  - climpred
  - fsspec
  - gcsfs
  - h5netcdf
  - nbgitpuller
  - pangeo-notebook >= 2020.10.08
  - pip
  - proplot
  - s3fs
  - pip:
      - git+https://github.com/intake/intake-esm@master